include game.inc

EXTERNDEF hero_left_0:Sprite
EXTERNDEF hero_left_1:Sprite
EXTERNDEF hero_left_2:Sprite
EXTERNDEF hero_left_3:Sprite
EXTERNDEF hero_right_0:Sprite
EXTERNDEF hero_right_1:Sprite
EXTERNDEF hero_right_2:Sprite
EXTERNDEF hero_right_3:Sprite
EXTERNDEF hero_stand:Sprite
EXTERNDEF mummy_left_1:Sprite
EXTERNDEF mummy_left_2:Sprite
EXTERNDEF mummy_right_1:Sprite
EXTERNDEF mummy_right_2:Sprite
EXTERNDEF bg:Sprite
